language: objective-c
osx_image: xcode7.3
before_install:
- gem install cocoapods
install:
- pod install
branches:
  only:
    - master
script:
  - set -o pipefail && xcodebuild -workspace Genoise.xcworkspace -scheme Genoise -sdk iphonesimulator9.3 build test | xcpretty --color
