# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
script: xcodebuild -workspace Example/Genoise.xcworkspace -scheme Genoise -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO