language: objective-c
osx_image: xcode7.3
before_install:
- gem install cocoapods
install:
- pod install --project-directory=Example/
branches:
  only:
    - master
script:
  - set -o pipefail && xcodebuild -workspace Example/Genoise.xcworkspace -scheme Genoise-Example -sdk iphonesimulator9.3 build test | xcpretty --color
